/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurant_s;

import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfWriter;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author alex
 */
public class Restaurants extends javax.swing.JFrame {
    
    double firstnum;
    double secondnum;
    double result;
    String operation;
    public static final double Naigerian_Naira = 397.04;
    public static final double Kenyan_Shiling = 128.59;
    public static final double US_Dollars = 1.26;
    public static final double Canadiyan_Dollars = 1.66;
    public static final double Brazilian_Reals = 4.25;
    public static final double Indian_Ruppe = 84.86;
    public static final double Philipins_Peso = 62.74;
    public static final double Indonesian = 16789.47;
    
    double[] i = new double[5];
    
    public Restaurants() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jtxtDisplay = new javax.swing.JTextField();
        jbtn7 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtnc = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtnequalto = new javax.swing.JButton();
        jbtnsub = new javax.swing.JButton();
        jbtnmul = new javax.swing.JButton();
        jbtnadd = new javax.swing.JButton();
        jbtndiv = new javax.swing.JButton();
        jbtndot = new javax.swing.JButton();
        jbtndel = new javax.swing.JButton();
        jbtnplusorminus = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jChickenBurger = new javax.swing.JCheckBox();
        jChickenBurgerMeal = new javax.swing.JCheckBox();
        jBaconAndChesse = new javax.swing.JCheckBox();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxSelectDrink = new javax.swing.JComboBox<>();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBoxHomeDelivery = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextCostOfDrink = new javax.swing.JTextField();
        jTextCostOfMeal = new javax.swing.JTextField();
        jTextCostOfDelivery = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        Total = new javax.swing.JButton();
        Receipt = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jComboBoxCurrency = new javax.swing.JComboBox<>();
        jTfCurrencyValue = new javax.swing.JTextField();
        Convert = new javax.swing.JButton();
        Close = new javax.swing.JButton();
        convertedValuelabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextFieldTax = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1150, 738));

        jPanel1.setBackground(new java.awt.Color(226, 226, 226));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel7.setBackground(new java.awt.Color(226, 226, 226));

        jtxtDisplay.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jtxtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jbtn7.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        jbtn7.setText("7");
        jbtn7.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });

        jbtn4.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        jbtn4.setText("4");
        jbtn4.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });

        jbtn1.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        jbtn1.setText("1");
        jbtn1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });

        jbtn0.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        jbtn0.setText("0");
        jbtn0.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });

        jbtn8.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        jbtn8.setText("8");
        jbtn8.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });

        jbtn5.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        jbtn5.setText("5");
        jbtn5.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });

        jbtn2.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        jbtn2.setText("2");
        jbtn2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });

        jbtnc.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        jbtnc.setText("C");
        jbtnc.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncActionPerformed(evt);
            }
        });

        jbtn3.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        jbtn3.setText("3");
        jbtn3.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });

        jbtn6.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        jbtn6.setText("6");
        jbtn6.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });

        jbtn9.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        jbtn9.setText("9");
        jbtn9.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });

        jbtnequalto.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        jbtnequalto.setText("=");
        jbtnequalto.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtnequalto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnequaltoActionPerformed(evt);
            }
        });

        jbtnsub.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        jbtnsub.setText("-");
        jbtnsub.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtnsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsubActionPerformed(evt);
            }
        });

        jbtnmul.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        jbtnmul.setText("*");
        jbtnmul.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtnmul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmulActionPerformed(evt);
            }
        });

        jbtnadd.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        jbtnadd.setText("+");
        jbtnadd.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnaddActionPerformed(evt);
            }
        });

        jbtndiv.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        jbtndiv.setText("/");
        jbtndiv.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtndiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndivActionPerformed(evt);
            }
        });

        jbtndot.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        jbtndot.setText(".");
        jbtndot.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtndot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndotActionPerformed(evt);
            }
        });

        jbtndel.setText("Del");
        jbtndel.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndelActionPerformed(evt);
            }
        });

        jbtnplusorminus.setFont(new java.awt.Font("Waree", 1, 14)); // NOI18N
        jbtnplusorminus.setText("%");
        jbtnplusorminus.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtnplusorminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnplusorminusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jtxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jbtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtndot, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnequalto, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addComponent(jbtndel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jbtnc, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel7Layout.createSequentialGroup()
                                                    .addComponent(jbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel7Layout.createSequentialGroup()
                                                    .addComponent(jbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtnplusorminus, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtnsub, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnmul, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtndiv, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jtxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtndel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnc, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnplusorminus, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jbtnsub, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnmul, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtndiv, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnequalto, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtndot, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Calculator", jPanel7);

        jPanel8.setBackground(new java.awt.Color(226, 226, 226));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Receipt", jPanel8);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(226, 226, 226));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jChickenBurger.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jChickenBurger.setText("Chicken burger");
        jChickenBurger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChickenBurgerMouseClicked(evt);
            }
        });

        jChickenBurgerMeal.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jChickenBurgerMeal.setText("Chicken burger Meal");
        jChickenBurgerMeal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChickenBurgerMealMouseClicked(evt);
            }
        });

        jBaconAndChesse.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jBaconAndChesse.setText("Bacon and  Cheese Burger");
        jBaconAndChesse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBaconAndChesseMouseClicked(evt);
            }
        });
        jBaconAndChesse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaconAndChesseActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });

        jTextField3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jTextField3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField3MouseEntered(evt);
            }
        });

        jTextField4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jTextField4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4MouseClicked(evt);
            }
        });
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel1.setText("Drinks:");

        jComboBoxSelectDrink.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jComboBoxSelectDrink.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Drink", "Apple Juice", "Tea", "Cocokola", "Coffe", "Orange Juice", "Ice Tea", "Ice Coffe", "Orange", " " }));
        jComboBoxSelectDrink.setBorder(null);
        jComboBoxSelectDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSelectDrinkActionPerformed(evt);
            }
        });

        jCheckBox4.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jCheckBox4.setText("Tax");
        jCheckBox4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox4MouseClicked(evt);
            }
        });

        jCheckBoxHomeDelivery.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jCheckBoxHomeDelivery.setText("Home Delivery");
        jCheckBoxHomeDelivery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxHomeDeliveryMouseClicked(evt);
            }
        });
        jCheckBoxHomeDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxHomeDeliveryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBaconAndChesse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jChickenBurgerMeal)
                            .addComponent(jChickenBurger))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(jTextField4)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxSelectDrink, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckBox4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBoxHomeDelivery)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jChickenBurger)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jChickenBurgerMeal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBaconAndChesse))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxSelectDrink))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxHomeDelivery)
                    .addComponent(jCheckBox4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(226, 226, 226));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel2.setText("Cost Of Drinks");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel3.setText("Cost Of Meal");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel4.setText("Cost of Delivery");
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextCostOfDrink.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextCostOfMeal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextCostOfMeal.setText("0");

        jTextCostOfDelivery.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextCostOfMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCostOfDrink, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCostOfDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextCostOfDrink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextCostOfMeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCostOfDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(226, 226, 226));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Total.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        Total.setText("Total");
        Total.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Total.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TotalMouseClicked(evt);
            }
        });
        Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalActionPerformed(evt);
            }
        });

        Receipt.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        Receipt.setText("Receipt");
        Receipt.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Receipt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReceiptMouseClicked(evt);
            }
        });
        Receipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceiptActionPerformed(evt);
            }
        });

        Reset.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        Reset.setText("Reset");
        Reset.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        Exit.setText("Exit");
        Exit.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(Receipt, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Receipt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(226, 226, 226));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jComboBoxCurrency.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jComboBoxCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose one", "USA", "Indian", "Nigeria", "Kenyan", "Canada", "Brazil", "Indonesia", "Philippine" }));
        jComboBoxCurrency.setBorder(null);
        jComboBoxCurrency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCurrencyActionPerformed(evt);
            }
        });

        jTfCurrencyValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTfCurrencyValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfCurrencyValueActionPerformed(evt);
            }
        });

        Convert.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        Convert.setText("Convert");
        Convert.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertActionPerformed(evt);
            }
        });

        Close.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        Close.setText("Close");
        Close.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        convertedValuelabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(Convert, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(Close, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBoxCurrency, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTfCurrencyValue)
                    .addComponent(convertedValuelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jComboBoxCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jTfCurrencyValue, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(convertedValuelabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Convert, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Close, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanel6.setBackground(new java.awt.Color(226, 226, 226));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel5.setText("Sub Total");

        jLabel6.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel6.setText("Tax");

        jLabel7.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel7.setText("Total");
        jLabel7.setBorder(null);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldTax, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Liberation Serif", 3, 24)); // NOI18N
        jLabel8.setText("Restaurant Management System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jComboBoxSelectDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSelectDrinkActionPerformed
        double Apple_Juice = 2.30;
        double Tea = 1.20;
        double Cocokola = 1.60;
        double Coffe = 2.50;
        double Orange_Juice = 3.20;
        double Ice_Tea = 1.25;
        double Ice_Coffe = 1.12;
        double Orange = 2.22;
        
        if (jComboBoxSelectDrink.getSelectedItem().equals("Apple Juice")) {
            String caj = String.format(" %.2f", Apple_Juice);
            jTextCostOfDrink.setText(caj);
        }
        
        if (jComboBoxSelectDrink.getSelectedItem().equals("Tea")) {
            String ct = String.format(" %.2f", Tea);
            jTextCostOfDrink.setText(ct);
        }
        
        if (jComboBoxSelectDrink.getSelectedItem().equals("Cocokola")) {
            String cc = String.format(" %.2f", Cocokola);
            jTextCostOfDrink.setText(cc);
        }
        
        if (jComboBoxSelectDrink.getSelectedItem().equals("Coffe")) {
            String ccf = String.format(" %.2f", Coffe);
            jTextCostOfDrink.setText(ccf);
        }
        
        if (jComboBoxSelectDrink.getSelectedItem().equals("Orange Juice")) {
            String coj = String.format(" %.2f", Orange_Juice);
            jTextCostOfDrink.setText(coj);
        }
        
        if (jComboBoxSelectDrink.getSelectedItem().equals("Ice Tea")) {
            String cit = String.format(" %.2f", Ice_Tea);
            jTextCostOfDrink.setText(cit);
        }
        
        if (jComboBoxSelectDrink.getSelectedItem().equals("Ice Coffe")) {
            String cic = String.format(" %.2f", Ice_Coffe);
            jTextCostOfDrink.setText(cic);
        }
        
        if (jComboBoxSelectDrink.getSelectedItem().equals("Orange")) {
            String co = String.format(" %.2f", Orange);
            jTextCostOfDrink.setText(co);
        }
        if (jComboBoxSelectDrink.getSelectedItem().equals("Select a Drink")) {
            jTextCostOfDrink.setText(null);
        }
        

    }//GEN-LAST:event_jComboBoxSelectDrinkActionPerformed

    private void jbtnsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsubActionPerformed
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operation = "-";
    }//GEN-LAST:event_jbtnsubActionPerformed

    private void jbtndotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndotActionPerformed
        jtxtDisplay.setText(jtxtDisplay.getText() + jbtndot.getText());
    }//GEN-LAST:event_jbtndotActionPerformed

    private void jbtndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndelActionPerformed
        String backspace = null;
        
        if (jtxtDisplay.getText().length() > 0) {
            StringBuilder sb = new StringBuilder(jtxtDisplay.getText());
            sb.deleteCharAt(jtxtDisplay.getText().length() - 1);
            backspace = sb.toString();
            jtxtDisplay.setText(backspace);
        }
    }//GEN-LAST:event_jbtndelActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        String Enternumber = jtxtDisplay.getText() + jbtn7.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        String Enternumber = jtxtDisplay.getText() + jbtn8.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
        String Enternumber = jtxtDisplay.getText() + jbtn9.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        String Enternumber = jtxtDisplay.getText() + jbtn4.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        String Enternumber = jtxtDisplay.getText() + jbtn5.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        String Enternumber = jtxtDisplay.getText() + jbtn6.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        String Enternumber = jtxtDisplay.getText() + jbtn1.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
        String Enternumber = jtxtDisplay.getText() + jbtn2.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        String Enternumber = jtxtDisplay.getText() + jbtn3.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
        String Enternumber = jtxtDisplay.getText() + jbtn0.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncActionPerformed
        jtxtDisplay.setText(null);
    }//GEN-LAST:event_jbtncActionPerformed

    private void jbtnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaddActionPerformed
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operation = "+";
    }//GEN-LAST:event_jbtnaddActionPerformed

    private void jbtndivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndivActionPerformed
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operation = "/";
    }//GEN-LAST:event_jbtndivActionPerformed

    private void jbtnmulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmulActionPerformed
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operation = "*";
    }//GEN-LAST:event_jbtnmulActionPerformed

    private void jbtnequaltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnequaltoActionPerformed
        String ans;
        secondnum = Double.parseDouble(jtxtDisplay.getText());
        
        if (operation == "+") {
            result = firstnum + secondnum;
            ans = String.format("%.2f", result);
            jtxtDisplay.setText(ans);
        } else if (operation == "-") {
            result = firstnum - secondnum;
            ans = String.format("%.2f", result);
            jtxtDisplay.setText(ans);
        } else if (operation == "*") {
            result = firstnum * secondnum;
            ans = String.format("%.2f", result);
            jtxtDisplay.setText(ans);
        } else if (operation == "/") {
            result = firstnum / secondnum;
            ans = String.format("%.2f", result);
            jtxtDisplay.setText(ans);
        } else if (operation == "%") {
            result = firstnum % secondnum;
            ans = String.format("%.2f", result);
            jtxtDisplay.setText(ans);
        }
    }//GEN-LAST:event_jbtnequaltoActionPerformed

    private void jbtnplusorminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnplusorminusActionPerformed
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operation = "%";
    }//GEN-LAST:event_jbtnplusorminusActionPerformed

    private void jTfCurrencyValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfCurrencyValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfCurrencyValueActionPerformed

    private void ConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertActionPerformed
        double British_Pound = Double.parseDouble(jTfCurrencyValue.getText());
        
        if (jComboBoxCurrency.getSelectedItem().equals("Nigeria")) {
            String cConvert1 = String.format("N %.2f", British_Pound * Naigerian_Naira);
            convertedValuelabel.setText(cConvert1);
        }
        
        if (jComboBoxCurrency.getSelectedItem().equals("USA")) {
            String cConvert1 = String.format("$ %.2f", British_Pound * US_Dollars);
            convertedValuelabel.setText(cConvert1);
        }
        
        if (jComboBoxCurrency.getSelectedItem().equals("Kenyan")) {
            String cConvert1 = String.format("KS %.2f", British_Pound * Kenyan_Shiling);
            convertedValuelabel.setText(cConvert1);
        }
        
        if (jComboBoxCurrency.getSelectedItem().equals("Canada")) {
            String cConvert1 = String.format("C$ %.2f", British_Pound * Canadiyan_Dollars);
            convertedValuelabel.setText(cConvert1);
        }
        
        if (jComboBoxCurrency.getSelectedItem().equals("Brazil")) {
            String cConvert1 = String.format("Bra %.2f", British_Pound * Brazilian_Reals);
            convertedValuelabel.setText(cConvert1);
        }
        
        if (jComboBoxCurrency.getSelectedItem().equals("Philippine")) {
            String cConvert1 = String.format("PHP %.2f", British_Pound * Philipins_Peso);
            convertedValuelabel.setText(cConvert1);
        }
        
        if (jComboBoxCurrency.getSelectedItem().equals("Indonesia")) {
            String cConvert1 = String.format("Rp %.2f", British_Pound * Indonesian);
            convertedValuelabel.setText(cConvert1);
        }
        
        if (jComboBoxCurrency.getSelectedItem().equals("Indian")) {
            String cConvert1 = String.format("INR %.2f", British_Pound * Indian_Ruppe);
            convertedValuelabel.setText(cConvert1);
        }
        
    }//GEN-LAST:event_ConvertActionPerformed

    private void jComboBoxCurrencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCurrencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCurrencyActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void jCheckBoxHomeDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxHomeDeliveryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxHomeDeliveryActionPerformed

    private void jCheckBoxHomeDeliveryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxHomeDeliveryMouseClicked
        double iDelivery = 3.39;
        if (jCheckBoxHomeDelivery.isSelected()) {
            String pDelivery = String.format(" %.2f", iDelivery);
            jTextCostOfDelivery.setText(pDelivery);
        } else {
            jTextCostOfDelivery.setText(null);
        }
    }//GEN-LAST:event_jCheckBoxHomeDeliveryMouseClicked

    private void ReceiptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReceiptMouseClicked
        
    }//GEN-LAST:event_ReceiptMouseClicked

    private void jChickenBurgerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChickenBurgerMouseClicked
        double cMeal;
        double cChickBurger;
        double iChickBurger = 2.39;
        double chickenburgercost;
        if (!jChickenBurger.isSelected()) {
            try {
                chickenburgercost = Double.parseDouble(jTextField2.getText()) * iChickBurger;
            } catch (Exception e) {
                chickenburgercost = 0.0;
            }
            double TotalCost = Double.parseDouble(jTextCostOfMeal.getText());
            double d = TotalCost - chickenburgercost;
            String s = String.format("%.2f", d);
            jTextField2.setText("");
            
            jTextCostOfMeal.setText(s);
        }
        
        try {
            cMeal = Double.parseDouble(jTextCostOfMeal.getText());
        } catch (Exception e) {
            cMeal = 0.0;
        }
        
        try {
            cChickBurger = Double.parseDouble(jTextField2.getText());
            
        } catch (Exception e) {
            cChickBurger = 0.0;
        }
        
        if (jChickenBurger.isSelected()) {
            i[0] = (cChickBurger * iChickBurger) + cMeal;
            String pMeal = String.format("%.2f", i[0]);
            jTextCostOfMeal.setText(pMeal);
        }
        

    }//GEN-LAST:event_jChickenBurgerMouseClicked

    private void jChickenBurgerMealMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChickenBurgerMealMouseClicked
        double cMeal;
        double cChickBurgerMeal;
        double iChickBurgerMeal = 3.49;
        double chickenburgermealcost;
        if (!jChickenBurgerMeal.isSelected()) {
            
            try {
                chickenburgermealcost = Double.parseDouble(jTextField4.getText()) * iChickBurgerMeal;
            } catch (Exception e) {
                chickenburgermealcost = 0.0;
            }
            double TotalCost = Double.parseDouble(jTextCostOfMeal.getText());
            double d = TotalCost - chickenburgermealcost;
            String s = String.format("%.2f", d);
            jTextField4.setText("");
            
            jTextCostOfMeal.setText(s);
        }
        
        try {
            cMeal = Double.parseDouble(jTextCostOfMeal.getText());
        } catch (Exception e) {
            cMeal = 0.0;
        }
        
        try {
            cChickBurgerMeal = Double.parseDouble(jTextField4.getText());
        } catch (Exception e) {
            cChickBurgerMeal = 0.0;
        }
        
        if (jChickenBurgerMeal.isSelected()) {
            i[1] = (cChickBurgerMeal * iChickBurgerMeal) + cMeal;
            String pMeal = String.format("%.2f", i[1]);
            jTextCostOfMeal.setText(pMeal);
        }
    }//GEN-LAST:event_jChickenBurgerMealMouseClicked

    private void jBaconAndChesseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBaconAndChesseMouseClicked
        double cMeal;
        double cBaconAndChesse;
        double iBaconAndChesse = 4.50;
        double baconandchesse;
        if (!jBaconAndChesse.isSelected()) {
            
            try {
                baconandchesse = Double.parseDouble(jTextField3.getText()) * iBaconAndChesse;
            } catch (Exception e) {
                baconandchesse = 0.0;
            }
            double TotalCost = Double.parseDouble(jTextCostOfMeal.getText());
            double d = TotalCost - baconandchesse;
            String s = String.format("%.2f", d);
            jTextField3.setText("");
            
            jTextCostOfMeal.setText(s);
        }
        
        try {
            cMeal = Double.parseDouble(jTextCostOfMeal.getText());
        } catch (Exception e) {
            cMeal = 0.0;
        }
        
        try {
            cBaconAndChesse = Double.parseDouble(jTextField3.getText());
        } catch (Exception e) {
            cBaconAndChesse = 0.0;
        }
        
        if (jBaconAndChesse.isSelected()) {
            i[2] = (cBaconAndChesse * iBaconAndChesse) + cMeal;
            String pMeal = String.format("%.2f", i[2]);
            jTextCostOfMeal.setText(pMeal);
        }
    }//GEN-LAST:event_jBaconAndChesseMouseClicked

    private void jCheckBox4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox4MouseClicked
        double cTotal1, cTotal2, cTotal3;
        
        if (jCheckBox4.isSelected()) {
            try {
                cTotal1 = Double.parseDouble(jTextCostOfDrink.getText());
            } catch (Exception e) {
                cTotal1 = 0.0;
            }
            
            try {
                cTotal2 = Double.parseDouble(jTextCostOfMeal.getText());
            } catch (Exception e) {
                cTotal2 = 0.0;
            }
            
            try {
                cTotal3 = Double.parseDouble(jTextCostOfDelivery.getText());
            } catch (Exception e) {
                cTotal3 = 0.0;
            }
            
            double allTotal = (cTotal1 + cTotal2 + cTotal3) / 100;
            String iTotal = String.format("%.2f", allTotal);
            jTextFieldTax.setText(iTotal);
        } else {
            jTextFieldTax.setText(null);
        }
    }//GEN-LAST:event_jCheckBox4MouseClicked

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        jChickenBurger.setSelected(false);
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jBaconAndChesseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaconAndChesseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBaconAndChesseActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        jTextField2.setText(null);
        jTextField4.setText(null);
        jTextField3.setText(null);
        jTfCurrencyValue.setText(null);
        convertedValuelabel.setText(null);
        jTextCostOfDrink.setText(null);
        jTextCostOfMeal.setText(null);
        jTextCostOfDelivery.setText(null);
        
        jCheckBox4.setSelected(false);
        jTextFieldTax.setText(null);
        jTextField9.setText(null);
        jTextField10.setText(null);
        jTextArea1.setText(null);
        jCheckBoxHomeDelivery.setSelected(false);
        jChickenBurger.setSelected(false);
        jChickenBurgerMeal.setSelected(false);
        jBaconAndChesse.setSelected(false);
    }//GEN-LAST:event_ResetActionPerformed

    private void TotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TotalMouseClicked
        double cTotal1, cTotal2, cTotal3, cTotal4;
        try {
            cTotal1 = Double.parseDouble(jTextCostOfDrink.getText());
        } catch (Exception e) {
            cTotal1 = 0.0;
        }
        
        try {
            cTotal2 = Double.parseDouble(jTextCostOfMeal.getText());
        } catch (Exception e) {
            cTotal2 = 0.0;
        }
        
        try {
            cTotal3 = Double.parseDouble(jTextCostOfDelivery.getText());
        } catch (Exception e) {
            cTotal3 = 0.0;
        }
        
        try {
            cTotal4 = Double.parseDouble(jTextFieldTax.getText());
        } catch (Exception e) {
            cTotal4 = 0.0;
        }
        
        double allTotal = (cTotal1 + cTotal2 + cTotal3 + cTotal4);
        double subTotal = (cTotal1 + cTotal2 + cTotal3);
        
        String itotal = String.format("£ %.2f", allTotal);
        String isubTotal = String.format("£ %.2f", subTotal);
        String itaxtotal = String.format("£ %.2f", cTotal4);
        
        jTextField9.setText(isubTotal);
        
        jTextField10.setText(itotal);
        
        jTextFieldTax.setText(itaxtotal);
        
    }//GEN-LAST:event_TotalMouseClicked

    private void TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalActionPerformed
    }//GEN-LAST:event_TotalActionPerformed

    private void jTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseClicked
        jChickenBurgerMeal.setSelected(false);
    }//GEN-LAST:event_jTextField4MouseClicked

    private void jTextField3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3MouseEntered

    private void jTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseClicked
        jBaconAndChesse.setSelected(false);
    }//GEN-LAST:event_jTextField3MouseClicked

    private void ReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceiptActionPerformed
        double qt1, qt2, qt3;
        
        try {
            qt1 = Double.parseDouble(jTextField2.getText());
            
        } catch (Exception e) {
            qt1 = 0.0;
        }
        
        try {
            qt2 = Double.parseDouble(jTextField4.getText());
            
        } catch (Exception e) {
            qt2 = 0.0;
        }
        
        try {
            qt3 = Double.parseDouble(jTextField3.getText());
        } catch (Exception e) {
            qt3 = 0.0;
        }
        
        jTextArea1.append("Restaurant Management System:\n\n"
                + "Chicken Burger:\t\t" + qt1
                + "\nChicken Burger Meal:\t\t" + qt2
                + "\nBacon and chesse Burger:\t\t" + qt3
                + "\n\n\tThanks For using System");
        String s = jTextArea1.getText();
        Document document = new Document();
        try {
            PdfWriter.getInstance(document, new FileOutputStream("receipt.pdf"));
        } catch (DocumentException ex) {
            Logger.getLogger(Restaurants.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Restaurants.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        document.open();
        try {
            document.add(new Paragraph(s));
        } catch (DocumentException ex) {
            Logger.getLogger(Restaurants.class.getName()).log(Level.SEVERE, null, ex);
        }
        document.close();
        
        
    }//GEN-LAST:event_ReceiptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurants().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Close;
    private javax.swing.JButton Convert;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Receipt;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Total;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel convertedValuelabel;
    private javax.swing.JCheckBox jBaconAndChesse;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBoxHomeDelivery;
    private javax.swing.JCheckBox jChickenBurger;
    private javax.swing.JCheckBox jChickenBurgerMeal;
    private javax.swing.JComboBox<String> jComboBoxCurrency;
    private javax.swing.JComboBox<String> jComboBoxSelectDrink;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextCostOfDelivery;
    private javax.swing.JTextField jTextCostOfDrink;
    private javax.swing.JTextField jTextCostOfMeal;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextFieldTax;
    private javax.swing.JTextField jTfCurrencyValue;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnadd;
    private javax.swing.JButton jbtnc;
    private javax.swing.JButton jbtndel;
    private javax.swing.JButton jbtndiv;
    private javax.swing.JButton jbtndot;
    private javax.swing.JButton jbtnequalto;
    private javax.swing.JButton jbtnmul;
    private javax.swing.JButton jbtnplusorminus;
    private javax.swing.JButton jbtnsub;
    private javax.swing.JTextField jtxtDisplay;
    // End of variables declaration//GEN-END:variables
}
